services:
  eureka:
    image: doussa1998/mini-project-eureka:latest
    container_name: eureka-serveur
    ports:
      - "8761:8761"
    environment:
      - spring.application.name=eureka
      - server.port=8761
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    networks:
      - projectMsA

  gateway:
    build: ./gateway  
    container_name: gateway
    ports:
      - "8082:8082"
    depends_on:
      - eureka
    environment:
      - spring.application.name=GATEWAY
      - server.port=8082
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true

    networks:
      - projectMsA

  event-management:
    image: doussa1998/mini-project-event:latest
    container_name: event
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    environment:
      - spring.application.name=EVENT-MANAGEMENT
      - server.port=8081
      - spring.datasource.url=jdbc:h2:mem:eventDB;DB_CLOSE_ON_EXIT=FALSE
      - spring.datasource.username=sa
      - spring.datasource.password=
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    networks:
      - projectMsA


  
  partenaires:
    build: ./gestionpartenaires
    container_name: gestion-partenaires
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - mysql
    environment:
      - spring.application.name=GESTIONPARTENAIRES
      - server.port=8083
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true
      - spring.datasource.url=jdbc:mysql://mysql:3306/gestionPartenairesDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.jpa.show-sql=true
      - spring.cloud.config.enabled=false
    networks:
      - projectMsA
  frontend:
    build: ./Eduport-Angular  # Assure-toi que le projet Angular est dans ./frontend
    container_name: angular-app
    ports:
      - "4200:4200"
    depends_on:
      - gateway
    networks:
      - projectMsA

  mysql:
      image: mysql:8.0
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      networks:
        - projectMsA
networks:
  projectMsA:
    driver: bridge
