services:
  eureka:
    build: ./Eureka
    image: firas16/mini-project-eureka:latest
    container_name: eureka-serveur
    ports:
      - "8761:8761"
    environment:
      - spring.application.name=eureka
      - server.port=8761
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    networks:
      - projectMsA

  gateway:
    build: ./Gateway
    image: firas16/mini-project-gateway:latest
    container_name: gateway
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - keycloak
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/JobBoardKeycloack
    networks:
      - projectMsA

  user-backend:
    build: ./userBackend
    image: firas16/mini-project-userbackend:latest # Replace with your image name if different
    container_name: usercontainer
    ports:
      - "8087:8087"
    command: [ "sh", "-c", "dockerize -wait tcp://mysql:3306 -timeout 30s && java -jar /app.jar" ]
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/db_Elearning?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    depends_on:
      - mysql
      - eureka
    networks:
      - projectMsA

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    networks:
      - projectMsA
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  event-management:
    build: ./EventManagement
    image: firas16/mini-project-event:latest
    container_name: event
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    environment:
      - spring.application.name=EVENT-MANAGEMENT
      - server.port=8081
      - spring.datasource.url=jdbc:h2:mem:eventDB;DB_CLOSE_ON_EXIT=FALSE
      - spring.datasource.username=sa
      - spring.datasource.password=
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    networks:
      - projectMsA

  feedback-service:
    build: ./Feedback-Serrvice
    image: firas16/mini-project-feedback:latest
    container_name: feedback
    ports:
      - "8086:8086"
    depends_on:
      - eureka
    environment:
      - spring.application.name=FEEDBACK-SERVICE
      - server.port=8086
      - spring.datasource.url=jdbc:h2:mem:feedbackdb;DB_CLOSE_ON_EXIT=FALSE
      - spring.datasource.username=sa
      - spring.datasource.password=
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    networks:
      - projectMsA

  keycloak:
    image: keycloak/keycloak:23.0.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: true
    networks:
      - projectMsA
    command: ["start-dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

  course-management:
    image: firas16/mini-project-course:latest
    container_name: course
    ports:
      - "9090:9090"
    depends_on:
      - eureka
      - mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - spring.datasource.url=jdbc:mysql://mysql:3306/gestioncourse?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
      - spring.datasource.username=root
      - spring.datasource.password=

      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    networks:
      - projectMsA

  partenaires:
    build: ./gestionpartenaires
    image: firas16/mini-project-partenaires:latest
    container_name: gestion-partenaires
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql:3306/gestionPartenairesDB?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
      - spring.datasource.username=root
      - spring.datasource.password=
    networks:
      - projectMsA


networks:
  projectMsA:
    driver: bridge
