services:
  eureka:
    image: doussa1998/mini-project-eureka:latest
    container_name: eureka-serveur
    ports:
      - "8761:8761"
    environment:
      - spring.application.name=eureka
      - server.port=8761
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    networks:
      - projectMsA

  gateway:
    image: doussa1998/mini-project-gateway:latest
    container_name: gateway
    ports:
      - "8082:8082"
    depends_on:
      - eureka
    environment:
      - spring.application.name=GATEWAY
      - server.port=8082
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    networks:
      - projectMsA

#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    networks:
#      - projectMsA

  course-management:
    image: aziz21a/course:latest
    container_name: course
    ports:
      - "9090:9090"
    depends_on:
      - eureka
#      - mysql
    environment:
      - spring.application.name=MICROSERVICE_COURSE_AZIZ
      - server.port=9090
#      - spring.datasource.url=jdbc:mysql://mysql:3306/gestioncourse?createDatabaseIfNotExist=true
#      - spring.datasource.username=root
#      - spring.datasource.password=
#      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    networks:
      - projectMsA

networks:
  projectMsA:
    driver: bridge
