e_learning:
    build: ./e_learning
    image: doussa1998/mini-project-microservice-file:latest
    container_name: file-container
    ports:
      - "8087:8087"
    depends_on:
      - eureka
      - mysql
    command: ["sh", "-c", "dockerize -wait tcp://mysql:3306 -timeout 30s && java -jar /app.jar"]
    environment:
      - spring.application.name=FILE-MANAGEMENT
      - server.port=8085
      - spring.datasource.url=jdbc:mysql://mysql:3306/fileDB?createDatabaseIfNotExist=true