services:
  eureka:
    image: doussa1998/mini-project-eureka:latest
    container_name: eureka-serveur
    ports:
      - "8761:8761"
    environment:
      - spring.application.name=eureka
      - server.port=8761
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    networks:
      - projectMsA

  gateway:
    image: doussa1998/mini-project-gateway:latest
    container_name: gateway
    ports:
      - "8082:8082"
    depends_on:
      - eureka
    environment:
      - spring.application.name=GATEWAY
      - server.port=8082
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    networks:
      - projectMsA


  mysqldba:
    image: mysql:8.0
    container_name: mysqldba
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - projectMsA

#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    networks:
#      - projectMsA

  course-management:
    image: aziz21a/course:latest
    container_name: course
    ports:
      - "9090:9090"
    depends_on:
      - eureka
      - mysqldba
    environment:
      - spring.application.name=COURSE
      - server.port=9090
      - spring.datasource.url=jdbc:mysql://mysqldba:3306/gestioncourse?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    networks:
      - projectMsA

networks:
  projectMsA:
    driver: bridge


volumes:
  db_data: